<a href="https://colab.research.google.com/github/Sandyon1top/Workshop1.AI/blob/main/Sandipdhakalworksheet1_2408003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
  print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [ ]:

import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
# Output: Inverse: [[-2. 1. ], [ 1.5 -0.5]]
print("Determinant:", np.linalg.det(A))
# Output: Determinant: -2.0
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
# Output: Frobenius Norm: 5.4772
print("2-Norm (Euclidean):", np.linalg.norm(A))
# Outptut: 2-Norm(Euclidean): 5.4772
print("Solution x:", np.linalg.solve(A, B))
#Output: Solution x: [-4. 4.5]


Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


In [ ]:

array = [[0, 0], [0, 0]]
print(array)

[[0, 0], [0, 0]]


In [ ]:
import numpy as np
array = np.ones((4, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

array = np.full((4, 2), 7)
print(array)

[[7 7]
 [7 7]
 [7 7]
 [7 7]]


In [ ]:
#4
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_array = np.zeros_like(array)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [ ]:
#5
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
ones_array = np.ones_like(array)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [ ]:
#6
import numpy as np

new_list = [1, 2, 3, 4]
array = np.array(new_list)
print(array)

[1 2 3 4]


In [ ]:
#1
import numpy as np

array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#2
import numpy as np

array = np.arange(9)
matrix = array.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4
import numpy as np

random_array = np.random.random(30)
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the Array:", mean_value)

Random Array: [0.9675461  0.33017706 0.44049487 0.34623551 0.64656012 0.79650098
 0.8675714  0.37943462 0.04148243 0.55030347 0.74231817 0.57265271
 0.93832211 0.11225321 0.86287161 0.14251404 0.99577705 0.84335702
 0.51170935 0.18226479 0.19618626 0.36118677 0.90853813 0.86481167
 0.56976557 0.95063828 0.90962051 0.07181173 0.0158607  0.03761229]
Mean of the Array: 0.5385459503831608


In [ ]:
#5
import numpy as np

random_array = np.random.random((10, 10))
min_value = random_array.min()
max_value = random_array.max()
print("Random 10x10 Array:\n", random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Random 10x10 Array:
 [[0.07366276 0.7369898  0.76467322 0.40834037 0.0191768  0.36207252
  0.26031893 0.73760092 0.34805307 0.85087285]
 [0.60409258 0.71130216 0.3890015  0.71245506 0.17113118 0.86873351
  0.53406077 0.70565901 0.07460274 0.60664004]
 [0.97150888 0.26928759 0.44113659 0.36336092 0.26755836 0.67442299
  0.17622844 0.67630269 0.20383765 0.64418456]
 [0.43046057 0.43113383 0.73701845 0.83762916 0.66442262 0.89516802
  0.70748705 0.65118846 0.69005674 0.10089751]
 [0.57729789 0.8554138  0.70499548 0.15006313 0.27734041 0.46169508
  0.7361037  0.77427377 0.64499865 0.79997042]
 [0.81403011 0.62573946 0.64648792 0.63129809 0.47237839 0.62209864
  0.31122992 0.85939413 0.38411882 0.81481626]
 [0.83082403 0.3113521  0.92412754 0.09926914 0.34318493 0.98540508
  0.30403601 0.68050632 0.74389037 0.40505917]
 [0.7880435  0.92432918 0.57142406 0.16384086 0.69579018 0.91508424
  0.0243002  0.27297676 0.72104838 0.12369581]
 [0.37708378 0.21855706 0.20271525 0.61692136 0.67690338 0.

In [ ]:
#6
import numpy as np
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7
import numpy as np

arr = np.array([1, 2, 5, 6, 7, 9])
reversed_arr = arr[::-1]
print(reversed_arr)

[9 7 6 5 2 1]


In [ ]:
#8
import numpy as np

size = 5
array = np.zeros((size, size), dtype=int)
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#9
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_result = x + y
subtract_result = x - y
multiply_result = x * 2
square_result = x**2

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

try:
    concat_xv = np.concatenate((x, v), axis=0)  #error
except ValueError as e:
    concat_xv_error = str(e)

print("1. Add:\n", add_result)
print("2. Subtract:\n", subtract_result)
print("3. Multiply:\n", multiply_result)
print("4. Square:\n", square_result)
print("5. Dot products:\n v.w =", dot_vw, "\n x.v =", dot_xv, "\n x.y =", dot_xy)
print("6. Concatenate x and y along rows:\n", concat_xy_row)
print("6. Concatenate v and w along columns:\n", concat_vw_col)
print("7. Concatenate x and v Error:\n", concat_xv_error)

1. Add:
 [[ 6  8]
 [10 13]]
2. Subtract:
 [[-4 -4]
 [-4 -3]]
3. Multiply:
 [[ 2  4]
 [ 6 10]]
4. Square:
 [[ 1  4]
 [ 9 25]]
5. Dot products:
 v.w = 219 
 x.v = [29 77] 
 x.y = [[19 22]
 [50 58]]
6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6. Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]
7. Concatenate x and v Error:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
#1. Prove A.A−1 = I.
import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
identity_result = np.dot(A, A_inv)
identity_matrix = np.eye(A.shape[0])  #generating identity matrix of the same size
is_identity = np.allclose(identity_result, identity_matrix)  #checking if almost equal

print("A:\n", A);
print("A^-1:\n", A_inv);
print("A * A^-1:\n", identity_result);
print("A * A^-1 equal to Identity matrix : ", is_identity);

A:
 [[3 4]
 [7 8]]
A^-1:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
A * A^-1 equal to Identity matrix :  True


In [ ]:
#2. Prove AB ̸= BA.
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
is_not_equal = not np.array_equal(AB, BA) #checking if AB = BA

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB not equal to BA : ", is_not_equal)

Matrix A:
 [[3 4]
 [7 8]]
Matrix B:
 [[5 3]
 [2 1]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB not equal to BA :  True


In [ ]:
#3. Prove (AB)^T = B^T.A^T
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
AB_T = np.transpose(AB)

B_T = np.transpose(B)
A_T = np.transpose(A)
BT_AT = np.dot(B_T, A_T)

#checking if (AB)^T == B^T A^T
is_equal = np.array_equal(AB_T, BT_AT)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("AB:\n", AB)
print("(AB)^T:\n", AB_T)
print("B^T:\n", B_T)
print("A^T:\n", A_T)
print("B^T A^T:\n", BT_AT)
print("(AB)^T equal to B^T A^T : ", is_equal)

Matrix A:
 [[3 4]
 [7 8]]
Matrix B:
 [[5 3]
 [2 1]]
AB:
 [[23 13]
 [51 29]]
(AB)^T:
 [[23 51]
 [13 29]]
B^T:
 [[5 2]
 [3 1]]
A^T:
 [[3 7]
 [4 8]]
B^T A^T:
 [[23 51]
 [13 29]]
(AB)^T equal to B^T A^T :  True


In [ ]:
#Linear equation using Inverse Methods
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)  #inverse of A
X = np.dot(A_inv, B)      #X = A^-1 * B

print("Coefficient matrix (A):\n", A)
print("Constant matrix (B):\n", B)
print("Inverse of A (A^-1):\n", A_inv)
print("Solution (X):\n", X)

Coefficient matrix (A):
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constant matrix (B):
 [-1 -3  9]
Inverse of A (A^-1):
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution (X):
 [ 2.  1. -2.]


In [ ]:
#1.1
import time

list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]
#measuring time for element-wise addition
start_time = time.time()
result = [x + y for x, y in zip(list1, list2)]
end_time = time.time()
time_taken = end_time - start_time

print(f"Time taken for element-wise addition of two lists is : {time_taken:.6f} seconds");

Time taken for element-wise addition of two lists is : 0.092925 seconds


In [ ]:
#1.2
import numpy as np
import time

array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)
#measuring time for element-wise addition
start_time = time.time()
result = array1 + array2
end_time = time.time()
time_taken = end_time - start_time

print(f"Time taken for element-wise addition of two NumPy arrays is : {time_taken:.6f} seconds");

Time taken for element-wise addition of two NumPy arrays is : 0.004682 seconds


In [ ]:
#2.1
import time

list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]
#measuring the time for element-wise multiplication
start_time = time.time()
result = [x * y for x, y in zip(list1, list2)]
end_time = time.time()
time_taken = end_time - start_time

print(f"Time taken for element-wise multiplication of two lists is ; {time_taken:.6f} seconds")

Time taken for element-wise multiplication of two lists is ; 0.133098 seconds


In [ ]:
#2.2
import numpy as np
import time

array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)
#measuring the time for element-wise multiplication
start_time = time.time()
result = array1 * array2
end_time = time.time()
time_taken = end_time - start_time

print(f"Time taken for element-wise multiplication of two NumPy arrays is : {time_taken:.6f} seconds")

Time taken for element-wise multiplication of two NumPy arrays is : 0.004696 seconds


In [ ]:
#3.1
import time

list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]
#measuring the time for dot product calculation
start_time = time.time()
dot_product = sum(x * y for x, y in zip(list1, list2))
end_time = time.time()
time_taken = end_time - start_time

print(f"Time taken for dot product of two lists is : {time_taken:.6f} seconds")

Time taken for dot product of two lists is : 0.104160 seconds


In [ ]:
#3.2
import numpy as np
import time

array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)
#measuring the time for dot product calculation
start_time = time.time()
dot_product = np.dot(array1, array2)
end_time = time.time()
time_taken = end_time - start_time

print(f"Time taken for dot product of two NumPy arrays is : {time_taken:.6f} seconds")

Time taken for dot product of two NumPy arrays is : 0.003023 seconds


In [ ]:
#4.1
import time

def matrix_multiply(A, B):
    size = len(A)
    #initiaizing the result matrix with zeros
    C = [[0] * size for _ in range(size)]

    #matrix multiplication
    for i in range(size):
        for j in range(size):
            for k in range(size):
                C[i][j] += A[i][k] * B[k][j]
    return C

#two random matrices of size 1000x1000
A = [[i + j for j in range(1000)] for i in range(1000)]
B = [[i * j for j in range(1000)] for i in range(1000)]
#measuring the time for matrix multiplication
start_time = time.time()
result = matrix_multiply(A, B)
end_time = time.time()
time_taken = end_time - start_time

print(f"Time taken for matrix multiplication of two 1000x1000 matrices is : {time_taken:.6f} seconds")

Time taken for matrix multiplication of two 1000x1000 matrices is : 329.048363 seconds


In [ ]:
#4.2
import numpy as np
import time

A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)
#measuring the time for matrix multiplication
start_time = time.time()
result = np.dot(A, B)
end_time = time.time()
time_taken = end_time - start_time

print(f"Time taken for matrix multiplication of two 1000x1000 matrices using NumPy is : {time_taken:.6f} seconds")

Time taken for matrix multiplication of two 1000x1000 matrices using NumPy is : 0.062444 seconds
